### PR TITLE
feat: Add to Trash

### PR DESCRIPTION
**Pull request by PeeyushPrashant**
- add to trash
- delete from trash
- restore from trash

Screenshot (113)
Screenshot (114)

### CODE REVIEW

**Review by Rohanmond — APPROVED** [review]
code looks good to merge

**Review by hrishi82 — APPROVED** [review]
code looks good, can be merged

**Review by ramalingaa — APPROVED** [review]
Code looks clean, backend implementation is good. PR can be merged

**Review by vinc3nati — APPROVED** [review]
Looks good

**Pull request merged**
